#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
z=1
while [ $ -le 10 ]
do
if [ $z -eq 4 ]
then
    echo '4'
    case "$4" in
	start)
	    start ;;
	stop)
	    stop ;;
	restart)
	    stop; start ;;
	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
    esac


    case EXPRESSION in

	PATTERN_1)
	    STATEMENTS
	    ;;

	PATTERN_2)
	    STATEMENTS
	    ;;

	PATTERN_N)
	    STATEMENTS
	    ;;

	*)
	    STATEMENTS
	    ;;
	esac