#!/usr/bin/env bash
#sing what did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
wget --spider -S "http://url/to/be/checked" 2>&1 | grep "HTTP/" | awk '{print $2}'
