#!/usr/bin/env bash
# This script let you display Best School 10 times using the while loop
valid=true
count=1
while [ $n -le 10 ]
do
echo "Best Shool"
if [ $count -eq 10 ];
then
break
fi
((count++))
done
