#!/usr/bin/env bash
# This script let you display Best School 10 times using the while loop
if [ $# -gt 0 ]; then

    filename=$1

    while read line; do
      
	echo "Best School"
    done < $filename
else
        echo "Best School"
