#!/usr/bin/env bash
# A Bash script that loops from 1 to 10
z=1
while [ $z -le 10]
      do
	  if [$z -eq 4 ]
	  then
	      echo 'bad luck'
	  elif [ $z -eq 8 ]
	       then
		   echo 'good luck'
	  else
	      echo 'Best School'
	  fi
	  ((z++))
	  done
