#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 using while,if,elif and else
name=snoopy

if [ "$name" = "snoopy" ] then
   echo "It was a dark and stormy night."
   elif [ "$name" == "charlie" ]
   then
	echo "You’re a good man Charlie Brown."
	elif [ "$name" == "lucy" ]
	then
		echo "The doctor is in."
		elif [ "$name" == "schroeder" ]
		then
			echo "In concert."
			else
				echo "Not a Snoopy character."
				fi