#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 
z=1
while [ z -le 20 ]
do
    case $z in

	if [$z -eq 4 ])
		       then
	    echo -n "bad luck from china"
	    ;;

		       elif [$z -eq 9 ])
then
	    echo -n "bad luck from Japan"
	    ;;

       else  [ $z -eq 17 ])
	    echo -n "bad luck from Italy"
	    ;;

	  esac
   
