#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
z=1
while [ $z != 21 ]
do
echo $z
    case $z in
	4)
	    echo "bad luck from china"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((z++))
done
