#!/usr/bin/env bash
#Write a manage_my_process Bash script that

PIDFILE=/var/run my process.pid
start () {
./manage_my_process &
echo "$!" > $PIDFILE)" && rm -f "$PIDFILE
}
stop() {
sudo kill-15 "$(cat $PIDFILE)
}
case "$1" in
start)
start
echo "manage_my_process started"
;;
stop)
stop
echo "manage_m_y process stopped"
;;
restart)
stop
start
echo "manage_my_process"restarted"
;;
*)
echo "usage/ manage_my_process
{start|stop|restart}"
esac
exit 0
