#!/usr/bin/env bash
#Write a manage_my_process Bash script that

while :
do
    echo 'I am alive! > /tmp/my_process
sleep 2
done
PIDFILE=/var/run/my_process &
echo ""£! > "$PIDFILE"
}

stop () {
sudo kill -15 "$(cat $PIDFILE)" && rm -f "$PIDEFILE"
}
casz "$1" in
start)
start
echo "manage_my_process started"
;;
restart)
stop)
stop
echo "manage_my_process stopped"
;;
*)
echo "Usage: manage_my_process
start|stop|restart}"
esac
exit 0
